project:
  type: website
  output-dir: "docs"

website:
  title: "aiart.dev"
  twitter-card: true
  favicon: favicon.ico
  site-url: "https://www.aiart.dev"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nateraw
      - icon: twitter
        href: https://twitter.com/_nateraw
  google-analytics: G-QQ37HV1W85

format:
  html:
    theme: lux
    css: styles.css

execute:
  freeze: auto